### PR TITLE
Add support for typescript

### PR DESCRIPTION
**Pull request by evanshortiss**
Hi @mrchimp!

Thanks for this module, I'm using it in a little web app I'm putting together. It uses TypeScript so I needed some type definitions for `tocktimer` to make it possible/easier to use.

If you'd like them added to the project that'd be great, but if not I can add them to the DefinitelyTyped repository instead.

I need to test this properly by installing this branch locally in a project, but will update shortly.

### CODE REVIEW

**Comment by mrchimp** [comment]
Hi Evan!

In general I'm happy to add Typescript support. However I've not actually used Typescript yet so I'm not sure what I'm letting myself in for. I'd want to do it right and understand what I'm doing or not at all.

Looking at your PR it seems pretty straight forward, I'm just wary of merging it and then breaking it with future updates.

Cheers!

**Comment by evanshortiss** [comment]
That's exactly the thing to consider, so good question.

Basically the `d.ts` file would need to be updated with any JavaScript API changes made in a release, e.g changing a function signature or adding/removing functions in tock. So the `d.ts` needs to align with the JavaScript interface in each release since it's essentially a descriptor for it. Then when someone does `npm install tocktimer -S` in a TypeScript project they'll be good to go!

Alternatively you could not include this typings file in the repo and let the responsibility fall to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/). This makes it easier for you as a maintainer (who might not care for TypeScript) to just push changes as needed and when it suits you. This does not ensure release parity between the types and underlying JS code since you might release `2.1.0` of tock tomorrow, but whoever uses tock might install the types as 2.0.0 from DefinitelyTyped so they have this in the package.json or similar:

```
{
  "dependencies" {
    "tocktimer" '2.1.0"
  },
  "devDependencies": {
    "@types/tocktimer": "2.0.0"
  }
}
```

When they realise they can be a good citizen and make a PR to DefinitelyTyped to update the `d.ts` there, or they might be lucky and have no issues and just carry on working 😄 

Let me know your thoughts on the maintenance overhead. If you feel it's not something you want to deal with (that's totally cool since some authors don't) I will open a PR in DefinitelyTyped since ultimately a type file will exist, it just lives in a separate place.

**Comment by mrchimp** [comment]
Ok, cool. I think for now I'll leave it up to DefinitelyTyped with a view to doing it properly once I get around to using TypeScript.

**Comment by evanshortiss** [comment]
Thanks for the update (and tocktimer)!

**Pull request closed without merging**
